name: build linux

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.27.0
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y keybinder-3.0 libayatana-appindicator3-dev ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: dart pub global activate flutter_distributor
      - run: flutter_distributor package --platform linux --targets deb
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${GITHUB_REF/refs\/tags\//}/cblm-${GITHUB_REF/refs\/tags\//}+${GITHUB_REF/refs\/tags\//}-linux.deb
          release_name: ${GITHUB_REF/refs\/tags\//}
          asset_name: cblm-${GITHUB_REF/refs\/tags\//}-linux-x86_64.deb
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: false