name: build linux

on:
  push:
    tags: [ '*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.27.0
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y keybinder-3.0 libayatana-appindicator3-dev ninja-build libgtk-3-dev
      - run: flutter config --enable-linux-desktop
      - run: dart pub global activate flutter_distributor
      - run: flutter_distributor package --platform linux --targets deb
      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ github.ref_name }}/cblm-${{ github.ref_name }}+${{ github.ref_name }}-linux.deb
          release_name: v${{ github.ref_name }}
          asset_name: cblm-v${{ github.ref_name }}-linux-x86_64.deb
          tag: ${{ github.ref }}
          overwrite: true
          prerelease: false